# Generated by Django 4.1.2 on 2024-03-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ewastecenters',
            old_name='center',
            new_name='name',
        ),
    ]
